### ISSUE TITLE
Missing sentences in QUAERO

### ISSUE THREAD

**Issue by Tiphaine-Lela** [qanastek/DrBERT#1]
Hi, 
I'd like to convert DrBERT's results on QUAERO to brat by modifying train_quaero.py, but some sentences seem to be missing at the end of the files when comparing with the brat files (e.g. 281_1 file in EMEA test). 
Thanks in advance!

**Comment by qanastek** [comment]
Hello Tiphaine,

Thank you very much for having noticed it!

Effectively, it's missing 2 sentences at the end of this document. We have updated the HuggingFace repository to fix this issue!

HF Datasets : https://huggingface.co/datasets/Dr-BERT/QUAERO

PS: If you are going to convert it back to the EMEA format to evaluate the model using the official evaluation scripts of QUAERO, please could you share it with us ?

Regards.

Yanis LABRAK

**Comment by Tiphaine-Lela** [comment]
Hello Yanis, 
Thank you for the update! It works fine.
